params = [
    {
        "n_units": 10000,
        "n_time": 84 * 2,
        "treatment_time": 84,
        "phi": 0.8,
        "sigma": 5,
        "alpha": 0.05,
        "seed": None,
        "bias": False,
        "constant_effect": True,
    },
    {
        "n_units": 10000,
        "n_time": 84 * 2,
        "treatment_time": 84,
        "phi": 0.8,
        "sigma": 1,
        "alpha": 0,
        "seed": None,
        "bias": True,
        "constant_effect": True,
    },
    {
        "n_units": 10000,
        "n_time": 84 * 2,
        "treatment_time": 84,
        "phi": 0.8,
        "sigma": 5,
        "alpha": 0.05,
        "seed": None,
        "bias": True,
        "constant_effect": True,
    },
    {
        "n_units": 10000,
        "n_time": 84 * 2,
        "treatment_time": 84,
        "phi": 0.8,
        "sigma": 5,
        "alpha": 0.05,
        "seed": None,
        "bias": True,
        "constant_effect": False,
    },
]
